Added action to invalidate cf cache

diff --git a/.github/workflows/deploy-staging-to-aws.yaml b/.github/workflows/deploy-staging-to-aws.yaml
--- a/.github/workflows/deploy-staging-to-aws.yaml
+++ b/.github/workflows/deploy-staging-to-aws.yaml
@@ -78,35 +78,35 @@ jobs:
           CF_RECORD_VALUE: ${{ needs.tf-staging-apply-run.outputs.CLOUDFRONT_DISTRIBUTION_01_DOMAIN_NAME }}
           CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
 
-#  cp-public-to-s3:
-#    runs-on: gha-runner-scale-set-amd64
-#    environment: staging
-#    needs: tf-staging-apply-run
-#    steps:
-#      - name: Checkout
-#        uses: actions/checkout@v4
-#      - name: Install aws cli and auth
-#        uses: v6Org01/.github/actions/install-cli-login-AWS@main
-#        with:
-#          AWS_REGION: ${{ vars.AWS_S3_BUCKET_01_REGION }}
-#          AWS_ROLE_ARN: "${{ secrets.AWS_ROLE_ARN }}"
-#      - name: Replace BASE_URL
-#        run: |
-#          find ./public -type f -exec sed -i 's|{{BASE_URL}}|'"${{ vars.HUGO_BASE_URL }}"'|g' {} +
-#      - name: Confirm BASE_URL replacement
-#        run: |
-#          if find ./public -type f -exec grep -l '{{BASE_URL}}' {} +; then
-#            echo "Error: {{BASE_URL}} was not replaced in some files."
-#            exit 1
-#          else
-#            echo "All {{BASE_URL}} placeholders have been successfully replaced."
-#          fi
-#      - name: Copy to S3
-#        run: |
-#          aws s3 sync ./public "s3://${{ needs.tf-staging-apply-run.outputs.S3_BUCKET_01_ID }}/${{ inputs.VERSION }}" --delete
-#      - name: Invalidate cloudfront cache
-#        run: |
-#          aws cloudfront create-invalidation --distribution-id ${{ needs.tf-staging-apply-run.outputs.CLOUDFRONT_DISTRIBUTION_01_ID }} --paths "/*"
+  invalidate-cf-cache:
+    runs-on: gha-runner-scale-set-amd64
+    environment: staging
+    needs: tf-staging-apply-run
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Install aws cli and auth
+        uses: v6Org01/.github/actions/install-cli-login-AWS@main
+        with:
+          AWS_REGION: ${{ vars.AWS_S3_BUCKET_01_REGION }}
+          AWS_ROLE_ARN: "${{ secrets.AWS_ROLE_ARN }}"
+#     - name: Replace BASE_URL
+#       run: |
+#         find ./public -type f -exec sed -i 's|{{BASE_URL}}|'"${{ vars.HUGO_BASE_URL }}"'|g' {} +
+#     - name: Confirm BASE_URL replacement
+#       run: |
+#         if find ./public -type f -exec grep -l '{{BASE_URL}}' {} +; then
+#           echo "Error: {{BASE_URL}} was not replaced in some files."
+#           exit 1
+#         else
+#           echo "All {{BASE_URL}} placeholders have been successfully replaced."
+#         fi
+#     - name: Copy to S3
+#       run: |
+#         aws s3 sync ./public "s3://${{ needs.tf-staging-apply-run.outputs.S3_BUCKET_01_ID }}/${{ inputs.VERSION }}" --delete
+      - name: Invalidate cloudfront cache
+        run: |
+          aws cloudfront create-invalidation --distribution-id ${{ needs.tf-staging-apply-run.outputs.CLOUDFRONT_DISTRIBUTION_01_ID }} --paths "/*"
 
   forward-var-version:
     runs-on: gha-runner-scale-set-arm64
